import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout-main/Sidebar";
import Topbar from "@/components/layout-main/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Collapsible sidebar state (stub, implement logic as needed)
  // const [collapsed, setCollapsed] = React.useState(false);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f7fafd] font-sans`}>
        {/* Header Bar */}
        <Topbar />
        {/* Main Layout */}
        <div className="flex pt-14 min-h-screen">
            <div className="hidden md:flex flex-col">
              <Sidebar />
            </div>
          {/* Content Area */}
          <main className="md:flex-1 ml-0  md:ml-64 p-8 overflow-y-auto h-[calc(100vh-3.5rem)] bg-gray-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
